import React from 'react'


import './analysing.css'

const Analysing = (props) => {
  return (
    <div className="analysing-container">
   
      <div className="analysing-frame332">
        <div className="analysing-frame383">
          <div className="analysing-readingglassesbro">
            <div className="analysing-backgroundsimple"></div>
            <div className="analysing-mug">
              <img
                alt="Vector3187"
                src="/external/vector3187-jn99.svg"
                className="analysing-vector"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-zm5n.svg"
                className="analysing-vector001"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-26u.svg"
                className="analysing-vector002"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-as8k.svg"
                className="analysing-vector003"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ci2f.svg"
                className="analysing-vector004"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-09vm.svg"
                className="analysing-vector005"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ck1.svg"
                className="analysing-vector006"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-2kzh.svg"
                className="analysing-vector007"
              />
            </div>
            <div className="analysing-books2">
              <img
                alt="Vector3187"
                src="/external/vector3187-w9yt.svg"
                className="analysing-vector008"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-5x3.svg"
                className="analysing-vector009"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-bh35.svg"
                className="analysing-vector010"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-p0xo.svg"
                className="analysing-vector011"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-n5he.svg"
                className="analysing-vector012"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-2s3.svg"
                className="analysing-vector013"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-t6pf.svg"
                className="analysing-vector014"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-vv5.svg"
                className="analysing-vector015"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-2k3l.svg"
                className="analysing-vector016"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-qtmf.svg"
                className="analysing-vector017"
              />
            </div>
            <div className="analysing-book1">
              <img
                alt="Vector3187"
                src="/external/vector3187-6od.svg"
                className="analysing-vector018"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-bis.svg"
                className="analysing-vector019"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-e7cui.svg"
                className="analysing-vector020"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-6hky.svg"
                className="analysing-vector021"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-fw8.svg"
                className="analysing-vector022"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ozeh.svg"
                className="analysing-vector023"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-9gyq.svg"
                className="analysing-vector024"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-8ntp.svg"
                className="analysing-vector025"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-o02k.svg"
                className="analysing-vector026"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-4ega.svg"
                className="analysing-vector027"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-kqm.svg"
                className="analysing-vector028"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-8rpo.svg"
                className="analysing-vector029"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-l694.svg"
                className="analysing-vector030"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-dvj2.svg"
                className="analysing-vector031"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-3fx.svg"
                className="analysing-vector032"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-xgi9.svg"
                className="analysing-vector033"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-cluh.svg"
                className="analysing-vector034"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-j5ya.svg"
                className="analysing-vector035"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7yvl.svg"
                className="analysing-vector036"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-isfj.svg"
                className="analysing-vector037"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ai3a.svg"
                className="analysing-vector038"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-xnvm.svg"
                className="analysing-vector039"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ux1.svg"
                className="analysing-vector040"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-yrnt.svg"
                className="analysing-vector041"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-uo6c.svg"
                className="analysing-vector042"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-y2i.svg"
                className="analysing-vector043"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-fp3l.svg"
                className="analysing-vector044"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-1a6.svg"
                className="analysing-vector045"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-vew8.svg"
                className="analysing-vector046"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-www.svg"
                className="analysing-vector047"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-cev.svg"
                className="analysing-vector048"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-wfz5.svg"
                className="analysing-vector049"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-j5d8.svg"
                className="analysing-vector050"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-skwhx.svg"
                className="analysing-vector051"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ow2f.svg"
                className="analysing-vector052"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-62i.svg"
                className="analysing-vector053"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-kp2e.svg"
                className="analysing-vector054"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-0ir.svg"
                className="analysing-vector055"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7xbh.svg"
                className="analysing-vector056"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-wdm.svg"
                className="analysing-vector057"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7w6cc.svg"
                className="analysing-vector058"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-zsl.svg"
                className="analysing-vector059"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-tdp7.svg"
                className="analysing-vector060"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-9x8l.svg"
                className="analysing-vector061"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-dta.svg"
                className="analysing-vector062"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-2g6f.svg"
                className="analysing-vector063"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-5ihs.svg"
                className="analysing-vector064"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-3xhb.svg"
                className="analysing-vector065"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-xlt.svg"
                className="analysing-vector066"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-rrv.svg"
                className="analysing-vector067"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-hto.svg"
                className="analysing-vector068"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-a2k8.svg"
                className="analysing-vector069"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-i6u.svg"
                className="analysing-vector070"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-rwo.svg"
                className="analysing-vector071"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-9gpd.svg"
                className="analysing-vector072"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-t7bg.svg"
                className="analysing-vector073"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-pqkl.svg"
                className="analysing-vector074"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ei6f.svg"
                className="analysing-vector075"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-fizub.svg"
                className="analysing-vector076"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ze02.svg"
                className="analysing-vector077"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-posh.svg"
                className="analysing-vector078"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-u9nct.svg"
                className="analysing-vector079"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-cxx.svg"
                className="analysing-vector080"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7loi.svg"
                className="analysing-vector081"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-9i0g.svg"
                className="analysing-vector082"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-9enp.svg"
                className="analysing-vector083"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-3m1.svg"
                className="analysing-vector084"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-i3wd.svg"
                className="analysing-vector085"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-fwpa.svg"
                className="analysing-vector086"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-l5oi.svg"
                className="analysing-vector087"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-dx2o.svg"
                className="analysing-vector088"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-uvqh.svg"
                className="analysing-vector089"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-eur.svg"
                className="analysing-vector090"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-p1va.svg"
                className="analysing-vector091"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-cnes.svg"
                className="analysing-vector092"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-m74f.svg"
                className="analysing-vector093"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-md4.svg"
                className="analysing-vector094"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-gjeq.svg"
                className="analysing-vector095"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-r4sl.svg"
                className="analysing-vector096"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-pndm.svg"
                className="analysing-vector097"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-eg3e.svg"
                className="analysing-vector098"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-keod.svg"
                className="analysing-vector099"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-laom.svg"
                className="analysing-vector100"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-lret.svg"
                className="analysing-vector101"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-h0ds.svg"
                className="analysing-vector102"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ffke.svg"
                className="analysing-vector103"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-lnkx.svg"
                className="analysing-vector104"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-d3ma.svg"
                className="analysing-vector105"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-seno.svg"
                className="analysing-vector106"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-31n3q.svg"
                className="analysing-vector107"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7pw.svg"
                className="analysing-vector108"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-plx.svg"
                className="analysing-vector109"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-cpuj.svg"
                className="analysing-vector110"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ozaa.svg"
                className="analysing-vector111"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-linb.svg"
                className="analysing-vector112"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-hsto.svg"
                className="analysing-vector113"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-5juj.svg"
                className="analysing-vector114"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-0j78.svg"
                className="analysing-vector115"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-rmle.svg"
                className="analysing-vector116"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-kice.svg"
                className="analysing-vector117"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-p73k.svg"
                className="analysing-vector118"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-h3tk.svg"
                className="analysing-vector119"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-td7w.svg"
                className="analysing-vector120"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-mazi.svg"
                className="analysing-vector121"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-t908.svg"
                className="analysing-vector122"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-7lf4.svg"
                className="analysing-vector123"
              />
            </div>
            <div className="analysing-glasses">
              <img
                alt="Vector3187"
                src="/external/vector3187-6jy.svg"
                className="analysing-vector124"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-y7q.svg"
                className="analysing-vector125"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-wu3.svg"
                className="analysing-vector126"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-76ke.svg"
                className="analysing-vector127"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-lds.svg"
                className="analysing-vector128"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-750u.svg"
                className="analysing-vector129"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ey9.svg"
                className="analysing-vector130"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-b92m.svg"
                className="analysing-vector131"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-zuw.svg"
                className="analysing-vector132"
              />
              <img
                alt="Vector3187"
                src="/external/vector3187-ptjm.svg"
                className="analysing-vector133"
              />
            </div>
          </div>
          <div className="analysing-frame407">
            <span className="analysing-text 14Medium">
              <span>Your prescription is being analysed</span>
            </span>
            <span className="analysing-text2 14Regular">
              <span>
                Give us a second. We will Notify you when your order is ready
              </span>
            </span>
          </div>
          <div className="analysing-frame410">
            <div className="analysing-frame408"></div>
            <div className="analysing-frame409"></div>
            <div className="analysing-frame4101"></div>
            <div className="analysing-frame411"></div>
          </div>
        </div>
        <span className="analysing-text4 14Medium">
          <span>Browse more products</span>
        </span>
      </div>
    </div>
  )
}

export default Analysing
