const data = [
    {
    "id":1,
     "productName": "Kapiva Noni Juice (1L) - Rich in Antioxidants, Boosts Energy, Builds Immunity, Natural Detoxifier",
     "Category": "Plant based supplement",
     "Brand": "Kapiva",
     "Discount coupon code & Discount expiry": "",
     "Storage Instructions": "Store in cool & dry place away from direct sunlight.",
     "Composition": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "Country of Origin": "India",
     "Adding Stock": 50,
     "Product Image": ["https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61az41InmzL._SL1080_.jpg"],
     "description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "count":0,
     "price":50,
     "Manufacturer":"Multicure Pharma Pvt Ltd",
     "prescriptionRequired":true,
     "unitsInPack": 1,
     "maxRetailPrice":230,
     "discount": 10,
     "sp":207
    },
    {
    "id":2,
     "productName": "Be Bodywise Biotin Hair Gummies for Stronger, Shinier Hair & Nails | 60 Day Pack",
     "Category": "Gummies",
     "Brand": "Be Bodywise",
     "Discount coupon code & Discount expiry": "",
     "Storage Instructions": "Store in cool & dry place away from direct sunlight",
     "Composition": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "Country of Origin": "India",
     "Adding Stock": 50,
     "Product Image": ["https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71jzruwYDvL._SL1500_.jpg"],
     "description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "count":0,
     "price":60,
     "Manufacturer":"Multicure Pharma Pvt Ltd",
     "prescriptionRequired":false,
     "unitsInPack": 1,
     "maxRetailPrice":85,
     "discount": 9,
     "sp":77
    },
    {
        "id":3,
     "productName": "Be Bodywise Gummies for Skin & Hair | Combo of 120 Gummies",
     "Category": "Gummies",
     "Brand": "Be Bodywise",
     "Discount coupon code & Discount expiry": "",
     "Storage Instructions": "Store in cool & dry place away from direct sunlight",
     "Composition": "Methyl salicylate, Diethyl phthalate, Castor oil, Industrial methylated spirit",
     "Country of Origin": "India",
     "Adding Stock": 50,
     "Product Image": ["https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/81QM5hbSfaL._SL1500_.jpg"],
     "description": "Multicure Doctor's Surgical Spirit I.P. is used as an antiseptic and disinfectant for cleaning and sanitizing wounds, cuts, and abrasions. It contains alcohol and can be used as a skin cleanser before surgery and injections.",
     "count":0,
     "price":70,
     "Manufacturer":"Multicure Pharma Pvt Ltd",
     "prescriptionRequired":true,
     "unitsInPack": 1,
     "maxRetailPrice":1500,
     "discount": 7,
     "sp":1399
    },
    {
        "id":4,
     "productName": "Nutrazee Multivitamin Gummies for Kids, Men & Women, Supplement With Biotin & Essential Vitamins For Healthy Growth, Development & Immunity, 45 Gummy Bears",
     "Category": "Gummies",
     "Brand": "Nutrazee",
     "Discount coupon code & Discount expiry": "",
     "Storage Instructions": "Store in cool & dry place away from direct sunlight",
     "Composition": "Glycerin",
     "Country of Origin": "India",
     "Adding Stock": 100,
     "Product Image": ["https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71-sv+HpjzL._SL1500_.jpg"],
     "description": "Our Rose glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying Rose glycerine to your skin may gradually improve its smoothness and suppleness",
     "count":0,
     "price":80,
     "Manufacturer":"Multicure Pharma Pvt Ltd",
     "prescriptionRequired":false,
     "unitsInPack": 1,
     "maxRetailPrice":590,
     "discount": 15,
     "sp":499
    },
    {
    "id":5,
     "productName": "Multimeds Rose Glycerin/Glycerine 100% Natural skin Moisturizing Skin Protectiton, Moisturizing, Dryness, Soft & Glowing Skin and hair (100G Pack of 1)",
     "Category": "Moisturizer",
     "Brand": "Multimeds Healthcare",
     "Discount coupon code & Discount expiry": "",
     "Storage Instructions": "Store in cool & dry place away from direct sunlight",
     "Composition": "Glycerin",
     "Country of Origin": "India",
     "Adding Stock": 100,
     "Product Image": ["https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61az41InmzL._SL1080_.jpg"],
     "description": "Our Rose glycerine has several skincare properties because of its moisturizing power. It is an all-purpose component in beauty products, including skin and hair care to treat areas suffering from itchiness and dryness. Applying Rose glycerine to your skin may gradually improve its smoothness and suppleness",
     "count":0,
     "price":90,
     "Manufacturer":"Multicure Pharma Pvt Ltd",
     "prescriptionRequired":true,
     "unitsInPack": 1,
     "maxRetailPrice":175,
     "discount": 15,
     "sp":149
    }
   ]

   export default data;


